### ISSUE TITLE
HomePage/Navbar

### ISSUE THREAD

**Issue by Abdullah-Naifeh** [Recoded-Spark-Turkey-2022/movie-project-movie-worm#2]
Navbar

- [x] Team/project logo

- [x] Home button

- [x] #13
genres)

- [x] Actor list button

- [x] About us button

- [x] #10

- [x] #11
in the home page based on the release date,
popular etc

**Comment by kogunlu** [comment]
The layout is completed. The functionality will be added to the search bar and movies dropdown list.

**Comment by kogunlu** [comment]
Movies dorpdown list is completed, functionality is done.
