### ISSUE TITLE
Single Movie Page

### ISSUE THREAD

**Issue by Abdullah-Naifeh** [Recoded-Spark-Turkey-2022/movie-project-movie-worm#9]
Single Movie Page should contain

- [x] The main 5 actors in the credit section => clicking will direct the user to the related actor's page 

- [x] Movie language

- [x] Related movies section which has at least 5 related movies 

- [x] A trailer section has a trailer from youtube 

- [x] Movie production company name and logo

- [ ] Director name

- [x] Movie rating and how many votes has it received 

- [ ] PS: There is an issue that needs to be fixed in the code, review it

**Comment by ghost** [comment]
Slick has been added. Single movie page is done.
